version: '3'

services:

  server:
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    environment:
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:5000
    volumes:
      - ./server:/srv/app/luceanne-server
    command: npm run start

  client:
    build: ./client
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:3000
    volumes:
      - ./client/src:/srv/app/luceanne-client/src
      - ./client/public:/srv/app/luceanne-client/public
    links:
      - server
    command: npm run start
